CREATE TABLE SIS_OWNER.COHORT_PROCESS_WINDOW
(
  COHORT_CD                 VARCHAR2(10 BYTE)   NOT NULL,
  S_PROCESS_TYPE            VARCHAR2(10 BYTE)   NOT NULL,
  SEQUENCE_NUMBER           NUMBER(6)           NOT NULL,
  TRANSACTION_LIMIT_NUMBER  NUMBER(6),
  CAL_TYPE                  VARCHAR2(10 BYTE)   NOT NULL,
  CI_SEQUENCE_NUMBER        NUMBER(6)           NOT NULL,
  START_DT_ALIAS            VARCHAR2(10 BYTE),
  START_SEQUENCE_NUMBER     NUMBER(6),
  START_TIME                DATE,
  END_DT_ALIAS              VARCHAR2(10 BYTE),
  END_SEQUENCE_NUMBER       NUMBER(6),
  END_TIME                  DATE,
  PREVENT_ACCESS_IND        VARCHAR2(1 BYTE)    DEFAULT 'N'                   NOT NULL,
  PREVENT_ACCESS_MESSAGE    VARCHAR2(2000 BYTE),
  UPDATE_WHO                VARCHAR2(30 BYTE)   DEFAULT SYS_CONTEXT('CALLISTA_CTX','USERNAME') NOT NULL,
  UPDATE_ON                 DATE                DEFAULT SYSDATE               NOT NULL
)

